
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Flaghere_production
  pool: 5
  host: localhost
  username: flaghere
  password: gpem4162
  socket: /var/run/mysqld/mysqld.sock
